{
  imports = [
    ./packages.nix
    ./bluetooth.nix
    ./shells.nix
    ./users.nix
    ./yubikey.nix
    ./hyprland.nix
    ./security.nix
    ./env.nix
    ./sound.nix
    ./network.nix
    ./bootloader.nix
    ./xserver.nix
    ./printing.nix
    ./greetd.nix
    ./nh.nix
    ./stylix.nix
  ];
}
